#!/bin/bash


# in the --geometry command the first value is equivalent to the width of the   
# terminal, the second is equivalent to the height of the terminal, the third   
# is equivalent to the y axis horizontal position relative to the screen, and   
# the fourth is equivalent to the x axis vertial position relative to the screen

# Setting up argument variables

COMMAND=$1
URL=$3

if [[ $# == 2 ]]; then
   DIRECTORY=$2
else
   DIRECTORY=$(pwd)
fi


if [[ $1 = '--help' ]]; then
  echo '''
Usage: term [OPTION]... [DIRECTORY]...

Open terminal windows evenly distributed on the screen.

   -r, --right             Opens two terminals on the right side of the screen.

   -l, --left              Opens two terminals on the left side of the screen.

   -t, --top               Opens two terminals on the top side of the screen.

   -b, --bottom            Opens two terminals on the bottom side of the screen.

   -tr, --topright         Open one terminal on the top right corner of the screen.

   -tl, --toplefti         Open one terminal on the top left corner of the screen.

   -br, --botrighti        Open one terminal on the bottom right corner of the screen.

   -bl, --botleft          Open one terminal on the bottom left corner of the screen.

   -3r, --threeright       Open three terminals one big on the right side of
                           the screen and two small ones on the left.

   -3l, --threeleft        Open three terminals one big on the left side of
                           the screen and two small ones on the right.

   -d, --directory         Open four terminals just as in term command but also
                           needs to pass the directory as an argument.

   -n, --netflix           Open three normal size terminals and an extra tab for
                           "enternteinment" with netflix. 

       --help              Display this help and exit.
    
       --version           Output the program version. 


  ''' 
   exit 

fi




#right (2)
if [[ $COMMAND = 'right' ]] || [[ $COMMAND = 'r' ]] || [[ $COMMAND = '-r' ]]; then
	gnome-terminal --geometry 125x30+970+35 --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+970+525 --working-directory=$DIRECTORY 

#left (2)
elif [[ $COMMAND = 'left' ]]  || [[ $COMMAND = 'l' ]] || [[ $COMMAND = '-l' ]]; then
	gnome-terminal --geometry 125x30+70+35 --working-directory=$DIRECTORY && 
	gnome-terminal --geometry 125x30+70+525 --working-directory=$DIRECTORY  

#top (2)
elif [[ $COMMAND = 'top' ]] || [[ $COMMAND = 't' ]] || [[ $COMMAND = '-t' ]]; then
	gnome-terminal --geometry 125x30+970+35 --working-directory=$DIRECTORY && 
	gnome-terminal --geometry 125x30+70+35 --working-directory=$DIRECTORY  

#bottom (2)
elif [[ $COMMAND = 'bottom' ]] || [[ $COMMAND = 'b' ]] || [[ $COMMAND = '-b' ]]; then
	gnome-terminal --geometry 125x30+970+525 --working-directory=$DIRECTORY && 
	gnome-terminal --geometry 125x30+70+525 --working-directory=$DIRECTORY  

#here are the options to open only one terminal, in a specific place top, right, bottom or left
#
#
#top-left
elif [[ $COMMAND = 'topleft' ]]  || [[ $COMMAND = 'tl' ]] || [[ $COMMAND = '-tl' ]]; then
	gnome-terminal --geometry 125x30+70+35 --working-directory=$DIRECTORY  


#bottom-left
elif [[ $COMMAND = 'botleft' ]]  || [[ $COMMAND = 'bl' ]] || [[ $COMMAND = '-bl' ]]; then
	gnome-terminal --geometry 125x30+70+525 --working-directory=$DIRECTORY 

#top-right
elif [[ $COMMAND = 'topright' ]]  || [[ $COMMAND = 'tr' ]] || [[ $COMMAND = '-tr' ]]; then
	gnome-terminal --geometry 125x30+970+35 --working-directory=$DIRECTORY


#bottom-right
elif [[ $COMMAND = 'botright' ]]  || [[ $COMMAND = 'br' ]] || [[ $COMMAND = '-br' ]]; then
	gnome-terminal --geometry 125x30+970+525 --working-directory=$DIRECTORY  

#make the option to three terminal windows                                      
elif [[ $COMMAND = '-3r' ]] || [[ $COMMAND = '--threeright' ]]; then
	gnome-terminal --geometry 125x30+70+35  --working-directory=$DIRECTORY &&     
	gnome-terminal --geometry 125x63+970+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+70+535 --working-directory=$DIRECTORY 

elif [[ $COMMAND = '-3l' ]] || [[ $COMMAND = '--threeleft' ]]; then
	gnome-terminal --geometry 125x30+970+35  --working-directory=$DIRECTORY &&     
	gnome-terminal --geometry 125x63+70+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+970+535 --working-directory=$DIRECTORY 


elif [[ $COMMAND = '-d' ]] || [[ $COMMAND = 'd' ]] || [[ $COMMAND = '--directory' ]]; then	
	gnome-terminal --geometry 125x30+70+35 --working-directory=$DIRECTORY && 
	gnome-terminal --geometry 125x30+970+35 --working-directory=$DIRECTORY && 
	gnome-terminal --geometry 125x30+70+525 --working-directory=$DIRECTORY && 
	gnome-terminal --geometry 125x30+970+525 --working-directory=$DIRECTORY 


elif [[ $COMMAND = '-n' ]] || [[ $COMMAND = 'netflix' ]]; then
	gnome-terminal --geometry 125x30+70+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+970+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+70+525  --working-directory=$DIRECTORY &&  
	# open netflix through and html file
	chromium --new-window /usr/local/sbin/term_js.html
#   chromium --new-window /usr/local/sbin/term_js.html?param_1=$URL


elif [[ $COMMAND = '-n1' ]] || [[ $COMMAND = 'netflix1' ]]; then
	gnome-terminal --geometry 125x30+70+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+970+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+70+525  --working-directory=$DIRECTORY &&  
	# open netflix through and html file
	chromium --new-window /usr/local/sbin/term_js.html
#   chromium --new-window /usr/local/sbin/term_js.html?param_1=$URL


elif [[ $COMMAND = '-n2' ]] || [[ $COMMAND = 'netflix2' ]]; then
	gnome-terminal --geometry 125x30+70+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+970+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+70+525  --working-directory=$DIRECTORY &&  
	# open netflix through and html file
	chromium --new-window /usr/local/sbin/term_js.html
#   chromium --new-window /usr/local/sbin/term_js.html?param_1=$URL


elif [[ $COMMAND = '-n3' ]] || [[ $COMMAND = 'netflix3' ]]; then
	gnome-terminal --geometry 125x30+70+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+970+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+70+525  --working-directory=$DIRECTORY &&  
	# open netflix through and html file
	chromium --new-window /usr/local/sbin/term_js.html
#   chromium --new-window /usr/local/sbin/term_js.html?param_1=$URL

elif [[ $COMMAND = '-n4' ]] || [[ $COMMAND = 'netflix4' ]]; then
	gnome-terminal --geometry 125x30+70+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+970+35  --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+70+525  --working-directory=$DIRECTORY &&  
	# open netflix through and html file
	chromium --new-window /usr/local/sbin/term_js.html
#   chromium --new-window /usr/local/sbin/term_js.html?param_1=$URL


else 
	gnome-terminal --geometry 125x30+70+35 --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+970+35 --working-directory=$DIRECTORY &&  
	gnome-terminal --geometry 125x30+70+525 --working-directory=$DIRECTORY && 
	gnome-terminal --geometry 125x30+970+525 --working-directory=$DIRECTORY  
fi

exit
